export default [
  {
    CELULAR: "3145789178",
    "NOMBRE CLIENTE": "MARTIN NAVARRO",
    SERVICIO: "AFILIACIONES",
    TIPO: "ENCUESTA",
  },
  {
    CELULAR: "3244533143",
    "NOMBRE CLIENTE": "DAVID CARREÑO",
    SERVICIO: "RESERVAS",
    TIPO: "CAMPAÑA",
  },
];
