name: Deploy CDK Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  # 👈 Asegura que se usen los secretos del entorno correcto

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Update Corepack to latest
        run: npm install -g corepack@latest

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install dependencies (root)
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Verify AWS authentication
        run: aws sts get-caller-identity

      - name: Build lambdas
        run: pnpm build
